### ISSUE TITLE
street grids quadratic?

### ISSUE THREAD

**Issue by gudrun-p** [TBIAPBC/APBC2022#38]
@mtw 
In the lecture, it was stated that all street grids in A3 are quadratic. However, it seems that this is not the case for all input files (at least Manhattan-testHV2.in seems to be rectangular). Is this a mistake with the input file, or was it a misunderstanding in the lecture?

**Comment by mtw** [comment]
Sorry for my late reply! In fact, they can be rectangular...I was too optimistic in the lecture ;)
